### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by rmuraix**
Fix typographical error in README.md

### CODE REVIEW

**Comment by daikikatsuragawa** [comment]
@rmuraix Thank you!

**Comment by daikikatsuragawa** [comment]
@rmuraix If possible, could you please correct the other typos as well? There are camel case or snake case error.

**Comment by rmuraix** [comment]
@daikikatsuragawa 
Are there camel case or snake case error in README? I could not find it.  
Or do you mean making Breaking changes to Action's input?

**Comment by daikikatsuragawa** [comment]
@rmuraix 
Sorry! I was mistaken...

**Pull request merged**
